import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";

import { BsTwitter, BsYoutube, BsLinkedin } from "react-icons/bs";
// import Image from "next/image";
// import deved from "../public/deved.jpg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dimitri Marco Portofolio</title>
        <meta name="description" content="Generated by crea" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl">DevelopedByCody</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill className="cursor-pointer text-2xl" />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-r from-cyan-500 to-teal-500 bg-cyan-500 text-white px-4 py-2 rounded-md ml-8"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 ">
            <h2 className="text-5xl py-2 text-teal-600 font-medium">
              Dimitri Marco
            </h2>
            <h3 className="text-2xl py-2">Developer and designer</h3>
            <p className="text-md py-5 leading-8 text-gray-800">
              Freelancer providing service for programming and degining product
              needs . Join me down below and let get cracking!
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600">
            <BsTwitter className="text-blue-600" />
            <BsLinkedin className="text-blue-600" />
            <BsYoutube className="text-red-500" />
          </div>
          <div className="w-80 mx-auto h-80 relative bg-gradient-to-b from-teal-500 rounded-full">
            {/* <Image src={deved} alt="" className="rounded w-60 h-60" /> */}
          </div>
        </section>
        <section className="mt-5">
          <div>
            <h3 className="text-3xl  text-teal-300 py-1 ml-[500px]">
              Services I Offer
            </h3>
            <p className="text-md py-2 w-80 mx-auto leading-8 text-gray-600">
              Since the beginning of my journey as a freelance designer and de c
              veloper I have done remote work for
              <span className="text-teal-500"> Agencies </span> consulted for
              <span>Standards</span> and collaboration withtalanted people to
              createa degine that suit our customer and statisfies them for
              bothbusiness and consumers use.
            </p>
          </div>
          <div>
            <div className=" ml-[600px] w-80 h-80 relative bg-gradient-to-b from-teal-500"></div>
            <h3 className="text-3xl text-teal-300 ml-[500px] ">
              Beautiful Designs
            </h3>
            <div className="ml-[550px]">
              <p className="py-2">
                Creating element design suited for your degin theory
              </p>
              <h4 className="py-4 text-teal-600 font-medium">
                Degin tools I use
              </h4>
              <p className="text-gray-800">Photoshop</p>
              <p className="text-gray-800">Illustrator</p>
              <p className="text-gray-800">Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl  text-teal-300 py-1 ml-[500px]">
              Portofolio
            </h3>
            <p className="text-md py-2 w-80 mx-auto leading-8 text-gray-600">
              Since the beginning of my journey as a freelance designer and de c
              veloper I have done remote work for
              <span className="text-teal-500"> Agencies </span> consulted for
              <span>Standards</span> and collaboration withtalanted people to
              createa degine that suit our customer and statisfies them for
              bothbusiness and consumers use.
            </p>
          </div>
        </section>
      </main>
    </>
  );
}
